"""add total_orders and total_value to customers
Revision ID: bd06e9d3412c
Revises: 6a07a5e6d141
Create Date: 2026-03-31 07:07:46.557666
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bd06e9d3412c'
down_revision: Union[str, None] = '6a07a5e6d141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=False, server_default='0', comment='Total number of completed sales for this customer'))
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=False, server_default='0.0', comment='Cumulative spend across all completed sales (GHS)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('total_value')
        batch_op.drop_column('total_orders')
    # ### end Alembic commands ###