"""add_purchase_receipt_to_adjustment_type

Revision ID: c51dd49549b1
Revises: 772f70aa66ed
Create Date: 2026-04-02 22:42:26.684793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51dd49549b1'
down_revision: Union[str, None] = '772f70aa66ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
